# Generated by Django 5.1.2 on 2024-10-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente',
            new_name='clientes',
        ),
    ]
