# Generated by Django 5.1.1 on 2024-10-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_cliente_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='razon_social',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='rif',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
